# https://github-wiki-see.page/m/mskcodes/canvas-lms/wiki/Production-Start
# https://github.com/dakshunt/canvas-lms/wiki/Production-Start

# below commands as root 
sudo -i 

# create swap file for small memory server because at least need 8GB
sudo dd if=/dev/zero of=/swapfile count=8096 bs=1MiB
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
swapon --show
swapon --summary
free -h
cat /etc/fstab

# create canvasuser as canvaslms application running 
sudo adduser --disabled-password --gecos canvas canvasuser

# add sudo as canvasuser  
echo "canvasuser ALL=(ALL:ALL) ALL" >> /etc/sudoers.d/011-canvasusers-sudoers

# ssl certbot for get ssl certificate  
apt-get install -y python-certbot-apache
certbot --non-interactive --agree-tos --redirect --hsts --uir -m email@yourdomain.com --apache -d yourdomain.com -d www.yourdomain.com

# update register for every 3 months
crontab -l | { cat; echo "30 2 * * * /usr/bin/certbot renew >> /var/log/le-renew.log"; } | crontab -

# check it saved ssl files
ls /etc/letsencrypt/

# apache install
apt-get install passenger libapache2-mod-passenger apache2
a2enmod rewrite
a2enmod passenger
a2enmod ssl
vi /etc/apache2/sites-available/canvas.conf

# delete don't need default file
unlink /etc/apache2/sites-enabled/000-default.conf
a2ensite canvas

# install postgresql 
apt-get install postgresql-9.5

sudo -u postgres createuser canvas --no-createdb --no-superuser --no-createrole --pwprompt
sudo -u postgres createdb canvas_production --owner=canvas
sudo -u postgres createuser $USER
sudo -u postgres psql -c "alter user $USER with superuser" postgres

# install ruby, nodejs, yarn
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.6 ruby2.6-dev zlib1g-dev libxml2-dev libsqlite3-dev postgresql libpq-dev libxmlsec1-dev curl make g++

sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install nodejs
sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn=1.10.1-1
sudo apt-get install python
yarn -v

# github clone canvaslms 
sudo apt-get install git-core
cd /var/canvas
git clone https://github.com/instructure/canvas-lms.git /var/canvas

# copy config files
for config in amazon_s3 database delayed_jobs domain file_store outgoing_mail security external_migration; do cp config/$config.yml.example config/$config.yml; done

# check ruby and install bundle gems
ruby -v
sudo gem install bundler --version 2.1.4
cd /var/canvas/
bundle _2.1.4_ install --path vendor/bundle
yarn install

# redis server install 
add-apt-repository ppa:chris-lea/redis-server
apt-get update
apt-get install redis-server

# copy redis config files
cd /var/canvas/
cp config/cache_store.yml.example config/cache_store.yml
vi config/cache_store.yml

chown canvasuser config/cache_store.yml

chmod 400 config/cache_store.yml
cp config/redis.yml.example config/redis.yml
vi config/redis.yml

chown canvasuser config/redis.yml
chmod 400 config/redis.yml

cd config
vi outgoing_mail.yml

cd config
vi domain.yml

cp config/dynamic_settings.yml.example config/dynamic_settings.yml

# below command as canvasuser 
su canvasuser

mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands
touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
touch Gemfile.lock
touch log/production.log

sudo chown -R canvasuser config/environment.rb log tmp public/assets app/stylesheets/_brandable_variables_defaults_autogenerated.scss                               app/stylesheets/brandable_css_brands Gemfile.lock config.ru
yarn install
# if need, but not required
yarn upgrade

# if you don't have minimum 8GB or swap, this time command show to you error. 
RAILS_ENV=production bundle exec rake canvas:compile_assets
RAILS_ENV=production bundle exec rake db:initial_setup

# below command do as root 
# permission change 
sudo chown -R canvasuser public/dist/brandable_css
sudo chown canvasuser config/*.yml
sudo chmod 400 config/*.yml

ln -s /var/canvas/script/canvas_init /etc/init.d/canvas_init
update-rc.d canvas_init defaults

chown www-data:www-data /var/canvas/public/

# Start    

/etc/init.d/canvas_init start
/etc/init.d/apache2 restart